### ISSUE TITLE
`packer::npm_update()` reports failure but update works

### ISSUE THREAD

**Issue by pvictor** [JohnCoene/packer#12]
Hi John,

When using `packer::npm_update()` it reports failure:

```r
> packer::npm_update()
x Failed to update
```

But modules are correctly updated.
You can try with https://github.com/dreamRs/bar, install use proportions-chart 1.1.2, update version 1.2.1.

Victor

**Comment by JohnCoene** [comment]
Strange it worked for me.

I ran `npm_install()` => `npm install`
then updated `npm_update()`

```json
{
  "devDependencies": {
    "webpack": "^5.46.0",
    "webpack-cli": "^4.2.0",
    "webpack-merge": "^5.4.0"
  },
  "dependencies": {
    "proportions-chart": "^1.2.1"
  }
}
```

Do you still encounter this issue with the latest version of packer?

**Comment by JohnCoene** [comment]
I'll assume this is fixed now (works on my end + tests) and close. Feel free to reopen if that is not the case.
