### ISSUE TITLE
Loader Rules Check

### ISSUE THREAD

**Issue by JohnCoene** [JohnCoene/packer#2]
Consider adding checks on loaders to avoiding duplicated entries and clashes.

**Comment by stewartli** [comment]
Hi John, 
Thank you for your amazing package. I really learn a lot. 
When I went through internals, I was unable to find the file shiny.js. Could you please point me in a direction? 
Reference: https://github.com/JohnCoene/packer/blob/master/inst/golem/javascript/index.js
Cheers.
![image](https://user-images.githubusercontent.com/35153517/90309125-91c5a300-df39-11ea-9214-d686c7a6ef48.png)


Regards, 
stewartli
