### ISSUE TITLE
Error in system2() while running scaffold_golem() from inside a golem app

### ISSUE THREAD

**Issue by shahreyar-abeer** [JohnCoene/packer#20]
Hi there,

I'm getting the following issue while trying to run `scaffold_golem()` from inside a golem app.

![image](https://user-images.githubusercontent.com/20732893/152281658-92da1120-657a-4e82-9812-f4f121c6bc18.png)

**Comment by JohnCoene** [comment]
Do you have nodejs and npm installed?

**Comment by shahreyar-abeer** [comment]
Sorry about that!
I forgot to install npm!
