### ISSUE TITLE
RS Connect can not see www/index.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by armenic** [JohnCoene/packer#24]
Dear developer, 

Thank you so much for an awesome package and a nice example of golem-react https://packer.john-coene.com/#/examples/golem-react
I followed your steps and it run fine locally on my machine. Then I run `golem::add_rstudioconnect_file()` to generate app.R for deploying to RS Connect. The full code I used is at https://github.com/armenic/reaction 

This is the content of app.R
```R
# Launch the ShinyApp (Do not remove this comment)
# To deploy, run: rsconnect::deployApp()
# Or use the blue button on top of this file

pkgload::load_all(export_all = FALSE,helpers = FALSE,attach_testthat = FALSE)
options( "golem.app.prod" = TRUE)
reaction::run_app() # add parameters here (if any)
```

Then I deployed it to RS Connect by uploading the whole package, every file. The app shows only the ui that comes from Shiny and fails to find the `index.js` 
```R
#' The application User-Interface
#'
#' @param request Internal parameter for `{shiny}`.
#'     DO NOT REMOVE.
#' @import shiny
#' @noRd
app_ui <- function(request) {
  fluidPage(
    h1("reaction"),
    tagList(
      reactCDN(),
      div(id = "app"),
      tags$script(src = "www/index.js")
    )
  )
}
```

```
GET https://connect.workbench.roche.com/content/fba9aaa6-ba0d-4090-b062-708d7fe0bbad/_w_945945ec/www/index.js net::ERR_ABORTED 404
```

![image](https://user-images.githubusercontent.com/71098506/172004588-5ec81b2f-20d3-4572-a2fb-56bc04eb334e.png)

**Comment by armenic** [comment]
The same issue happens on shnyapps.io, pleas see https://armenic.shinyapps.io/reaction/

**Comment by JohnCoene** [comment]
It's an issue with the guide on the website, apologies.

It's missing `golem_add_external_resources` in the UI, [here](https://github.com/armenic/reaction/blob/4ad542a4dccc6ccdcf6bdaf997401b81952dbd57/R/app_ui.R#L7) should be

```r
app_ui <- function(request) {
  fluidPage(
    golem_add_external_resources(),
    h1("reaction"),
    tagList(
      reactCDN(),
      div(id = "app"),
      tags$script(src = "www/index.js")
    )
  )
}
```

**Comment by armenic** [comment]
You are amazing @JohnCoene, thank you so much for the fix as well as update to React 18 💯
