### ISSUE TITLE
Svelte Example

### ISSUE THREAD

**Issue by asbates** [JohnCoene/packer#27]
I recently noticed that `packer` has a function `use_loader_svelte`. This is super interesting because I've been thinking lately about how to use Svelte in a Shiny app. However I'm struggling to come up with a working example.

Do you have any examples of using Svelte with Shiny? If not I'm happy to add one to the `packer` docs if and when I finally get an example together.

**Comment by asbates** [comment]
OK, I may have spoke too soon. I managed to put together a [very simple app](https://github.com/asbates/packerSvelteTest). Hopefully I can extend this to something more realistic.

**Comment by JohnCoene** [comment]
Sorry I did not answer, it's been a hectic week. I can maybe find the time to add a page in the doc on what you did, it looks good!
