### ISSUE TITLE
look for the file - shiny.js

### ISSUE THREAD

**Issue by stewartli** [JohnCoene/packer#4]
Hi John,
Thank you for your amazing package. I really learn a lot.
When I went through internals, I was unable to find the file shiny.js. Could you please point me in a direction?
Reference: https://github.com/JohnCoene/packer/blob/master/inst/golem/javascript/index.js
Cheers.
![image](https://user-images.githubusercontent.com/35153517/90309159-dea97980-df39-11ea-8a9b-6c4c2b80e939.png)

Regards,
stewartli

**Comment by JohnCoene** [comment]
Glad you like! :)

shiny is imported as external, having the file would work but would duplicate it as dependency as `shiny::fluidPage` and `shiny::navbarPage` would re-import it I think.

So instead it's imported external [here](https://github.com/JohnCoene/packer/blob/master/inst/common/webpack.common.js#L34)

```js
{
  externals: {
    shiny: 'window.Shiny'
  }
}
```

You can read more about it [here](https://webpack.js.org/configuration/externals/). Does that answer your question?

**Comment by stewartli** [comment]
Hi John, thank you very much for the links. excellent. 'v'

**Comment by stewartli** [comment]
Hi John, thank you very much for the links. excellent. 'v'
