### ISSUE TITLE
npm_install() not working on windows

### ISSUE THREAD

**Issue by benjaminschwetz** [JohnCoene/packer#5]
Hi, 
I tried to use packer on windows and noticed that the `npm_*` example doesn't really work. 

``` r
packer::npm_install("sass", scope = "dev")
#> i Installing sass with scope dev[Kx Failed to install sass[K
```

I spotted that, for windows, it should probably be where instead of which in npm_find(), but I didn't have time to really look into it further.
``` r
packer:::npm_find()
#> Error in system2("which", "npm", stdout = TRUE): '"which"' not found
npm_find <- function () 
{
  npm <- getOption("JS4R_NPM", NULL)
  if (is.null(npm)) 
    npm <- suppressWarnings(system2("where", "npm", 
                                    stdout = TRUE))
  return(npm)
}
npm_find()
#> [1] "C:\\Program Files\\nodejs\\npm"     "C:\\Program Files\\nodejs\\npm.cmd"
```

<sup>Created on 2020-10-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by JohnCoene** [comment]
Hi Benjamin,

Sorry for getting to this so late. I've had a few hectic weeks, I pushed what I think should fix it.

Let me know if this does not work and I can take another look.

Thanks!
