### ISSUE TITLE
Permission denied when using packer::scaffold_ functions

### ISSUE THREAD

**Issue by ajmoralesa** [JohnCoene/packer#7]
Thanks for this amazing package!

I'm having issues to get it work in Ubuntu 18.04.3 LTS. When running any of the `packer::scaffold_` functions, I get: 

![image](https://user-images.githubusercontent.com/25555632/103162088-b4bb6a00-47eb-11eb-852a-8e6103687cb4.png)

It looks like a `webpack` related issue but I am unable to fix it using the proposed solutions [here](https://github.com/pro-react/react-app-boilerplate/issues/5#issuecomment-324379695) or [here](https://github.com/pro-react/react-app-boilerplate/issues/5#issuecomment-232673783). 

Could this be directly related to the way `packer` deals with `webpack`?

**Comment by JohnCoene** [comment]
Apologies for the late response, I'm not sure why this issue escaped me.

I looks like it's the path to NPM that is not correct (status 126), 1) it's not NPM and 2) it's not an executable. If running `which npm` from the terminal returns a path then there is no need to use `set_npm`; packer will automatically find the installed version.

**Comment by JohnCoene** [comment]
I'm gonna go ahead and close this. Feel free to reopen if this is still stands.
